-- MySQL Script generated by MySQL Workbench
-- Fri May  9 19:02:08 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LittleLemonDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LittleLemonDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LittleLemonDB` DEFAULT CHARACTER SET utf8 ;
USE `LittleLemonDB` ;

-- -----------------------------------------------------
-- Table `LittleLemonDB`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`Customers` (
  `Customer_ID` INT NOT NULL AUTO_INCREMENT,
  `First_Name` VARCHAR(75) NOT NULL,
  `Last_Name` VARCHAR(75) NOT NULL,
  `Phone_Number` INT NOT NULL,
  `Email_Address` VARCHAR(100) NULL,
  PRIMARY KEY (`Customer_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`Staff_Members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`Staff_Members` (
  `Staff_Member_ID` INT NOT NULL AUTO_INCREMENT,
  `First_Name` VARCHAR(75) NOT NULL,
  `Last_Name` VARCHAR(75) NOT NULL,
  `Role` VARCHAR(50) NOT NULL,
  `Salary` DECIMAL(12,2) NULL,
  PRIMARY KEY (`Staff_Member_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`Bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`Bookings` (
  `Booking_ID` INT NOT NULL AUTO_INCREMENT,
  `Customer_ID` INT NOT NULL,
  `Date` DATE NOT NULL,
  `Time` TIME NOT NULL,
  `Table_Number` INT NULL,
  `Staff_Member_ID` INT NULL,
  PRIMARY KEY (`Booking_ID`),
  INDEX `Customer_ID_FK_idx` (`Customer_ID` ASC) VISIBLE,
  INDEX `Staff_ID_FK_idx` (`Staff_Member_ID` ASC) VISIBLE,
  CONSTRAINT `Customer_ID_FK_1`
    FOREIGN KEY (`Customer_ID`)
    REFERENCES `LittleLemonDB`.`Customers` (`Customer_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Staff_Member_ID_FK`
    FOREIGN KEY (`Staff_Member_ID`)
    REFERENCES `LittleLemonDB`.`Staff_Members` (`Staff_Member_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`Menus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`Menus` (
  `Menu_ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(50) NOT NULL,
  `Type` VARCHAR(50) NOT NULL,
  `Cuisine` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Menu_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`Orders` (
  `Order_ID` INT NOT NULL AUTO_INCREMENT,
  `Customer_ID` INT NOT NULL,
  `Date` DATE NOT NULL,
  `Time` TIME NOT NULL,
  `Total_Cost` DECIMAL(10,2) NOT NULL,
  `Menu_ID` INT NOT NULL,
  `Total_Items` INT NOT NULL,
  PRIMARY KEY (`Order_ID`),
  INDEX `Customer_ID_FK_idx` (`Customer_ID` ASC) VISIBLE,
  INDEX `Menu_ID_FK_idx` (`Menu_ID` ASC) VISIBLE,
  CONSTRAINT `Customer_ID_FK_2`
    FOREIGN KEY (`Customer_ID`)
    REFERENCES `LittleLemonDB`.`Customers` (`Customer_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Menu_ID_FK`
    FOREIGN KEY (`Menu_ID`)
    REFERENCES `LittleLemonDB`.`Menus` (`Menu_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`Menu_Items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`Menu_Items` (
  `Menu_Item_ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(75) NOT NULL,
  `Type` VARCHAR(50) NOT NULL,
  `Cost` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`Menu_Item_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`Order_Statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`Order_Statuses` (
  `Order_Status_ID` INT NOT NULL AUTO_INCREMENT,
  `Order_ID` INT NOT NULL,
  `Date` DATE NULL,
  `Time` TIME NULL,
  `Status` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Order_Status_ID`),
  INDEX `Order_ID_FK_idx` (`Order_ID` ASC) VISIBLE,
  CONSTRAINT `Order_ID_FK_1`
    FOREIGN KEY (`Order_ID`)
    REFERENCES `LittleLemonDB`.`Orders` (`Order_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`Order_Items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`Order_Items` (
  `Order_Item_ID` INT NOT NULL AUTO_INCREMENT,
  `Order_ID` INT NOT NULL,
  `Menu_Item_ID` INT NOT NULL,
  `Quantity` INT NOT NULL,
  PRIMARY KEY (`Order_Item_ID`),
  INDEX `Order_ID_FK_idx` (`Order_ID` ASC) VISIBLE,
  INDEX `Menu_Item_ID_FK_idx` (`Menu_Item_ID` ASC) VISIBLE,
  CONSTRAINT `Order_ID_FK_2`
    FOREIGN KEY (`Order_ID`)
    REFERENCES `LittleLemonDB`.`Orders` (`Order_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Menu_Item_ID_FK`
    FOREIGN KEY (`Menu_Item_ID`)
    REFERENCES `LittleLemonDB`.`Menu_Items` (`Menu_Item_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
